import axios from 'axios';
import React, { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useParams } from 'react-router-dom';
import Nav from '../Navbar/Nav';
import classes from './main.module.scss'


export default function Main() {
  const [user, setUser] = useState('')
  const nav = useNavigate();
  useEffect(() => {
    if(localStorage.getItem('token') == ''){
      nav('/login')
    }
    axios.get(`http://localhost:8082/users/${JSON.parse(localStorage.getItem('token')).login}`)
    .then(res => {
      if(res.data[0] == undefined){
        localStorage.setItem('token', '')
        nav('/login')
      }
      setUser(res.data[0])})
    .catch(err => console.log(err))
  },[])
  const logout = () => {
    localStorage.setItem('token', '');
    nav('/login')
  }
  return (
    <div>
      <Nav/>
      <Link to={`/profile/${user.id}`}>Profile</Link>
      <Link to='/login' onClick={logout}>Logout</Link>
      <Link to='/posts'>Posts</Link>
      <ul>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
        <li>
          awdawdad
        </li>
      </ul>
    </div>
  )
}
